Repository aiida-vasp/aiida-vasp, pull requests merged in 2018-08, with the labels that each got.

#188 Refactor the VaspParser by moving setup of quantities and parsers to …
  aiida_vasp/io/parser.py
  aiida_vasp/io/tests/test_doscar_io.py
  aiida_vasp/io/tests/test_eigenval_io.py
  aiida_vasp/io/tests/test_vasprun_io.py
  aiida_vasp/io/vasprun.py
  aiida_vasp/parsers/file_parser_definitions.py
  aiida_vasp/parsers/parser_manager.py
  aiida_vasp/parsers/parser_settings.py
  aiida_vasp/parsers/quantity.py
  aiida_vasp/parsers/tests/test_parser_settings.py
  aiida_vasp/parsers/tests/test_vasp_parser.py
  aiida_vasp/parsers/vasp.py
  aiida_vasp/utils/delegates.py
  aiida_vasp/utils/extended_dicts.py
  aiida_vasp/utils/fixtures/data.py
Labels: code quality

#193 fix the potcar command to work with aiida develop
  aiida_vasp/commands/options.py
  aiida_vasp/commands/potcar.py
  aiida_vasp/utils/aiida_utils.py
Labels: bug, p0 - critical

#197 Removed obsolete/redundant 'parsers' card from quantity_definitions
  aiida_vasp/io/chgcar.py
  aiida_vasp/io/doscar.py
  aiida_vasp/io/eigenval.py
  aiida_vasp/io/kpoints.py
  aiida_vasp/io/outcar.py
  aiida_vasp/io/poscar.py
  aiida_vasp/io/vasprun.py
  aiida_vasp/io/wavecar.py
  aiida_vasp/parsers/parser_manager.py
  aiida_vasp/parsers/quantity.py
  aiida_vasp/parsers/tests/test_vasp_parser.py
Labels: code quality

#201 fix links in README to point to the aiida-team repo
  README.rst
Labels: bug, documentation
